[package]
name = "qimen-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "PyO3 bindings for qimen-core"
publish = false

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]
test = false
doctest = false

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.29.2", features = ["abi3-py310"] }
qimen-core = { path = "../../crates/qimen-core", version = "0.1.0" }

[lints]
workspace = true
