[package]
name = "qimen-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "WebAssembly bindings for qimen-core"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
test = false
doctest = false

[dependencies]
qimen-core = { path = "../../crates/qimen-core", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.128"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lints]
workspace = true
